---
# load_config task
#
- name: initialize function
  include_tasks: includes/init.yaml

- name: validate task arguments
  validate_role_spec:
    spec: load_config_spec.yaml

- name: lookup config file
  set_fact:
    dmos_config_text: "{{ lookup('config_template', dmos_config_file) | join('\n') }}"
  when: dmos_config_file != ''

- name: Include configure task
  include_tasks: includes/configure/configure.yaml
  when: not ansible_check_mode and not dmos_config_replace
